name: Build and Test

on:
  pull_request:
    branches: [ "main" ]
    
concurrency:
  group: build-ios-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
  
    runs-on: macos-latest
    
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=15,name=iPhone 13']
          
    steps:
      - uses: actions/checkout@v3
      
      - name: Build
        run: |
          xcodebuild clean build -project AndreChallenge.xcodeproj -scheme AndreChallenge -destination "${destination}"
        env: 
         destination: ${{ matrix.destination }}
         
      - name: Test
        run: |
          xcodebuild clean test -project AndreChallenge.xcodeproj -scheme AndreChallenge -destination "${destination}"
        env: 
         destination: ${{ matrix.destination }}
